repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -  id: trailing-whitespace
- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.5.11
  hooks:
    # Update the uv lockfile
    - id: uv-lock
- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.5.11
  hooks:
    - id: uv-export
      args: ["--frozen", "--output-file=requirements-custom.txt"]