repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -  id: trailing-whitespace
# - repo: https://github.com/astral-sh/uv-pre-commit
#   # uv version.
#   rev: 0.5.8
#   hooks:
#   - id: uv-export
#   - args: [--no-hashes, --format, requirements-txt, new_requirements.txt"]