name: debug
dump_dir: /workspace/AI-Uncomplicated/
seed: 42
grad_acc_steps: 32
gc_collect_freq: 1000
probe_freq: null
steps: 10000
data:
  data_path: /workspace/AI-Uncomplicated/core/models/text_to_sql/schema_linkage/data/schema_linkage_dataset.jsonl
  batch_size: 32
  seq_len: 1024
  n_views: 2
  seed: 42
  prefetch_size: 64
  tokenizer:
    name: Qwen/Qwen2.5-0.5B-Instruct
    add_system_prompt: True
    add_template: True
    add_special_tokens: True
optim:
  lr: 0.0003
  weight_decay: 0.1
  epsilon: 1.0e-08
  beta1: 0.9
  beta2: 0.95
  clip: 10.0
  scheduler: wsd
  warmup: 2000
  lr_min_ratio: 1.0e-06
  cycle_length: 1.0
  cosine_theta: 1.0
  annealing_step: 1000
  decay_fraction: 0.1
  decay_type: cosine
  exp_factor: 0.5
model:
  name: Qwen/Qwen2.5-0.5B-Instruct
distributed:
  dp_shard: 2
  dp_replicate: 1
  selective_activation_checkpointing: false
  compile: true
  fsdp_type: full_shard
  model_dtype: bf16
  float8_recipe: null
  float8_filter: layers\.[0-9]+\.
  matmul_allow_tf32: false
  allow_bf16_reduced_precision_reduction: true
  detect_anomaly: false
  compile_cache_size_limit: 8
  spawn_method: forkserver
env:
  MKL_SERVICE_FORCE_INTEL: GNU
  OMP_NUM_THREADS: '1'
  MKL_NUM_THREADS: '1'
  ENABLE_INTRA_NODE_COMM: '1'
  TORCH_NCCL_AVOID_RECORD_STREAMS: '1'
  NCCL_IB_TIMEOUT: '22'
  NCCL_DEBUG: INFO
  TORCH_NCCL_ASYNC_ERROR_HANDLING: '1'
checkpoint:
  save_every:
    step: 1000
    limit: 0
  eval_every:
    step: 1000
    limit: 0
  path: /workspace/AI-Uncomplicated/
  init_ckpt_path: null
  continue_training_from_init: false
profiling:
  run: false
  trace_folder: profiling
  mem_warmup: 100
  mem_steps: 2
  profile_warmup: 102
  profile_steps: 2
logging:
  freq: 1
  acc_freq: null
  wandb:
    job_type: null
    dir: /workspace/AI-Uncomplicated/wandb/
    project: Pretrain
    entity: jaganmathematics
    tags: null
    group: null
    name: qwen_0.5_schema_linkage_kick_starter
    notes: null
    config_exclude_keys: null
    config_include_keys: null
    anonymous: null
    mode: null
    allow_val_change: null
    resume: null
    force: null
    tensorboard: null
    sync_tensorboard: null
    monitor_gym: null
    save_code: null
    id: null
    fork_from: null
    resume_from: null
async_eval_gpus: null
eval: null
